apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: emergent-microservice-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 8
  metrics:
  - type: External
    external:
      metricName: "custom.googleapis.com|response_time1"
      targetValue: 105
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emergent-microservice