apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: sd-exporter
  name: sd-exporter
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sd-exporter
  template:
    metadata:
      labels:
        run: sd-exporter
    spec:
      containers:
      - command: ["./direct-to-sd"]
        args: ["--metric-name=response_time1", "--pod-id=$(POD_ID)"]
        image: docker.io/robertovrf/sd-exporter:all
        name: exporter222
        ports:
        - containerPort: 8081
 
        resources:
          requests:
            cpu: 100m
        env:
          - name: POD_ID
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.uid
